server:
  port: ${PORT:8080}

spring:
  application:
    name: XenoShopSync

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:953869001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:aWSJsqrdC6NHZf27}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${MAIL_FROM:w.shaik28835@gmail.com}

app:
  jwt:
    secret: ${JWT_SECRET:dev-super-secret-key-1234567890-abcdefghijklmnopqrstuvwxyzletsgowithyourchicken}
    issuer: ${JWT_ISSUER:waseem}
    access-minutes: ${JWT_ACCESS_MINUTES:1440}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:xeno-dusky.vercel.app}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
