server:
  port: 8080

spring:
  application:
    name: XenoShopSync

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:salary_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 953869001@smtp-brevo.com   # your email, injected from env
    password: aWSJsqrdC6NHZf27   # app password / smtp password from env
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from:
      w.shaik28835@gmail.com

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:

    secret: dev-super-secret-key-1234567890-abcdefghijklmnopqrstuvwxyzletsgowithyourchicken
    issuer: waseem
    # Access token lifetime
    access-minutes: 1440

  cors:
    allowed-origins: xeno-dusky.vercel.app
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

